Repository victorhoffmann/projeto-integrador, pull requests merged in 2021-03, with the labels that each got.

#1 feature/home-teste
  Home/home.css
  Home/home.html
  assets/img/headset1.jpg
Labels: enhancement

#2 ajustando header, carousel e footer
  Home/home.css
  assets/img/headset2.jpg
  assets/img/headset3.jpg
  index.html
  style.css
Labels: enhancement

#3 feature: corrigindo responsividade
  style.css
Labels: enhancement

#5 Feature/04 contato
  Pages/Contato/contato.css
  Pages/Contato/contato.html
  Pages/Sobre/scripts/tilt.js
  Pages/Sobre/sobre.css
  Pages/Sobre/sobre.html
Labels: enhancement

#4 feature: criando o corpo da pagina sobre
  Pages/Sobre/scripts/tilt.js
  Pages/Sobre/sobre.css
  Pages/Sobre/sobre.html
Labels: documentation

#6 feature 01 - criando a página minhaConta
  Pages/MinhaConta/minhaConta.css
  Pages/MinhaConta/minhaConta.html
Labels: enhancement

#7 feature: finalizando pagina de reenvios
  Pages/MinhaConta/Reenvio/esqueciLogin.html
  Pages/MinhaConta/Reenvio/esqueciSenha.html
  Pages/MinhaConta/Reenvio/reenvio.css
  Pages/MinhaConta/minhaConta.css
  Pages/MinhaConta/minhaConta.html
  assets/img/btn_enviar.png
Labels: enhancement

#8 feature: inicializando react-app
  .gitignore
  README.md
  backup-html-css/README.md
  backup-html-css/assets/img/btn_enviar.png
  backup-html-css/assets/img/headset1.jpg
  backup-html-css/assets/img/headset2.jpg
  backup-html-css/assets/img/headset3.jpg
  backup-html-css/index.html
  backup-html-css/pages/Contato/contato.css
  backup-html-css/pages/Contato/contato.html
  backup-html-css/pages/MinhaConta/Reenvio/esqueciLogin.html
  backup-html-css/pages/MinhaConta/Reenvio/esqueciSenha.html
  backup-html-css/pages/MinhaConta/Reenvio/reenvio.css
  backup-html-css/pages/MinhaConta/minhaConta.css
  backup-html-css/pages/MinhaConta/minhaConta.html
  backup-html-css/pages/Sobre/scripts/tilt.js
  backup-html-css/pages/Sobre/sobre.css
  backup-html-css/pages/Sobre/sobre.html
  backup-html-css/style.css
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/index.css
  src/index.js
  src/logo.svg
Labels: enhancement

#9 feature: estruturando arquivos
  backup-html-css/README.md
  backup-html-css/index.html
  backup-html-css/style.css
  public/index.html
  src/App.css
  src/App.js
  src/assets/btn_enviar.png
  src/assets/headset1.jpg
  src/assets/headset2.jpg
  src/assets/headset3.jpg
  src/components/Aside/index.js
  src/components/Aside/style.css
  src/components/Footer/index.js
  src/components/Footer/style.css
  src/components/Header/index.js
  src/components/Header/style.css
  src/components/Main/index.js
  src/components/Main/style.css
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/Contato/contato.css
  src/pages/Contato/contato.html
  src/pages/Home/index.js
  src/pages/MinhaConta/Reenvio/esqueciLogin.html
  src/pages/MinhaConta/Reenvio/esqueciSenha.html
  src/pages/MinhaConta/Reenvio/reenvio.css
  src/pages/MinhaConta/minhaConta.css
  src/pages/MinhaConta/minhaConta.html
  src/pages/Sobre/scripts/tilt.js
  src/pages/Sobre/sobre.css
  src/pages/Sobre/sobre.html
Labels: enhancement

#10 feature 01 - passando pagina minha conta para React
  src/pages/MinhaConta/minhaConta.js
Labels: enhancement

#11 feature 01 passando a pagina Sobre para o react
  src/components/MainMinhaConta/index.js
  src/components/MainMinhaConta/style.css
  src/components/MainSobre/index.js
  src/components/MainSobre/style.css
  src/pages/MinhaConta/index.js
  src/pages/MinhaConta/minhaConta.html
  src/pages/Sobre/index.js
Labels: enhancement

#14 Fix/01-corrigindo-rotas
  src/components/Footer/index.js
  src/components/MainMinhaConta/index.js
  src/components/MainSobre/index.js
  src/components/MainSobre/scripts/tilt.js
  src/index.js
  src/pages/Sobre/index.js
Labels: bug

#15 finalizando nova estruturação de login
  src/assets/btn_enviar.png
  src/components/Cadastrar/index.js
  src/components/Cadastrar/style.css
  src/components/Entrar/index.js
  src/components/Entrar/style.css
  src/components/Header/index.js
  src/components/MainMinhaConta/index.js
  src/components/MainMinhaConta/style.css
  src/components/Senha/index.js
  src/index.css
  src/pages/Cadastro/index.js
  src/pages/Login/ReenvioSenha/index.js
  src/pages/Login/index.js
  src/pages/MinhaConta/Reenvio/esqueciLogin.html
  src/pages/MinhaConta/Reenvio/esqueciSenha.html
  src/pages/MinhaConta/Reenvio/reenvio.css
  src/pages/MinhaConta/index.js
  src/routes/index.js
Labels: enhancement

#16 finalizando pagina FAQ
  src/components/Footer/index.js
  src/pages/Faq/index.js
  src/pages/Faq/style.css
  src/routes/index.js
Labels: enhancement

#18 feature/09-todosProdutos
  .gitignore
  src/assets/monitor1.jpg
  src/assets/monitor2.jfif
  src/assets/monitor3.jfif
  src/components/CardTodosProdutos/index.js
  src/components/CardTodosProdutos/style.css
  src/components/Header/index.js
  src/components/MainContato/index.js
  src/components/ShelfTodosProdutos/index.js
  src/components/ShelfTodosProdutos/style.css
  src/pages/Faq/index.js
  src/pages/TodosProdutos/index.js
  src/routes/index.js
Labels: enhancement

#23 feature01: conteúdo visual geral da página do carrinho
  src/components/Header/index.js
  src/components/MainCarrinho/index.js
  src/components/MainCarrinho/style.css
  src/pages/Carrinho/index.js
  src/routes/index.js
Labels: enhancement

#25 feature: aplicando border-radius
  src/components/Header/style.css
  src/components/MainCarrinho/style.css
Labels: enhancement
